apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  selector:
    matchLabels:
      app: spring-petclinic
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-petclinic
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: app
          image: ghcr.io/pavolloffay/spring-petclinic:latest
          resources:
            limits:
              memory: "256M"
              cpu: "0.3"
            requests:
              memory: "128M"
              cpu: "0.1"
