apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 5s
        static_configs:
          - targets: ['otel-collector.default.svc.cluster.local:8888']
          - targets: ['otel-collector.default.svc.cluster.local:8889']