apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation
  namespace: sock-shop
spec:
  env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://localhost:4317
    - name: OTEL_METRICS_EXPORTER
      value: otlp
  exporter:
    endpoint: http://localhost:4317
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  java:
    env:
      - name: OTEL_JAVAAGENT_DEBUG
        value: "true"



