apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  ports:
  - name: grpc-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: internal-prometheus-metrics
    port: 8888
    protocol: TCP
    targetPort: 8888
  - name: collected-prometheus-metrics
    port: 8889
    protocol: TCP
    targetPort: 8889
  selector:
    app.kubernetes.io/name: otel-collector
  type: ClusterIP